// <auto-generated />
namespace FlightTracker5.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class first_shot : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(first_shot));
        
        string IMigrationMetadata.Id
        {
            get { return "202102182346488_first_shot"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
